# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  workflow_call:
    inputs:
      config-file:
        description: Path to the custard config file.
        type: string
        required: true
      head-sha:
        description: The commit sha of the head where the changes live.
        type: string
        required: true
      main-sha:
        description: The commit sha of the main branch to be compared to.
        default: origin/main
        type: string
      paths:
        description: Comma-separated package paths instead of git diff.
        type: string
      custard-version:
        description: Custard version to install.
        type: string
        default: v0.0.6  # x-release-please-version
      create-check-if:
        description: Creates a check if true, otherwise no check is created.
        type: boolean
        default: true
      check-name:
        description: Name of the check created by this workflow.
        type: string
        default: Custard CI

    outputs:
      paths:
        description: The affected paths as a JSON list.
        value: ${{ jobs.affected.outputs.paths }}
      num-paths:
        description: The number of affected paths.
        value: ${{ jobs.affected.outputs.num-paths }}
      ci-setups:
        description: The CI setup configurations for the affected packages.
        value: ${{ jobs.affected.outputs.ci-setups }}
      check:
        description: The check that was created by this job.
        value: ${{ jobs.affected.outputs.check }}

jobs:
  affected:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    outputs:
      paths: ${{ steps.custard.outputs.paths }}
      num-paths: ${{ steps.custard.outputs.num-paths }}
      ci-setups: ${{ steps.custard.outputs.ci-setups }}
      check: ${{ steps.final_status.outputs.check }}
    timeout-minutes: 2
    steps:
      - name: Check queued
        uses: glasnt/trifle/actions/steps/create-check@v0.0.5
        id: queued
        with:
          sha: ${{ inputs.head-sha }}
          name: ${{ inputs.check-name }}
          status: queued
          title: Finding affected packages
          job-name: ${{ github.job }}
          if: ${{ inputs.create-check-if }}
      - name: Find affected packages
        uses: glasnt/trifle/actions/steps/affected@v0.0.5
        id: custard
        with:
          config-file: ${{ inputs.config-file }}
          head-sha: ${{ inputs.head-sha }}
          main-sha: ${{ inputs.main-sha }}
          paths: ${{ inputs.paths }}
          custard-version: ${{ inputs.custard-version }}
      - name: Check in_progress
        uses: glasnt/trifle/actions/steps/update-check@v0.0.5
        id: in_progress
        with:
          check: ${{ steps.queued.outputs.check }}
          status: in_progress
          title: Running ${{ steps.custard.outputs.num-paths }} package(s)
      - name: Check success
        uses: glasnt/trifle/actions/steps/update-check@v0.0.5
        id: final_status
        if: success()
        with:
          check: ${{ steps.queued.outputs.check }}
          status: success
          title: Completed finding ${{ steps.custard.outputs.num-paths }} package(s)
      - name: Check failure
        uses: glasnt/trifle/actions/steps/update-check@v0.0.5
        if: failure()
        with:
          check: ${{ steps.queued.outputs.check }}
          status: failure
